POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "jjokunen",
    "password": "salainen",
    "name": "Jaska Jokunen"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "iasimov",
    "password": "huonosalasana",
    "name": "Isaac Asimov"
}